# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 08:36
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, default=b'', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=b'', max_length=512, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=b'title', unique=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tag_id', models.CharField(blank=True, db_index=True, default=b'', max_length=255, null=True)),
                ('main_link', models.URLField(db_index=True, default=b'')),
                ('sub_link', models.URLField(db_index=True, default=b'', unique=True)),
                ('published', models.CharField(blank=True, db_index=True, default=b'', max_length=255, null=True)),
                ('updated', models.CharField(blank=True, db_index=True, default=b'', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
