# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0002_auto_20171211_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='sub_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appes.Sublink'),
        ),
    ]
