# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0003_auto_20171211_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='sub_link',
            field=models.URLField(blank=True, db_index=True, default=b'', max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Sublink',
        ),
    ]
