# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0005_auto_20171211_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='sub_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
