# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 10:47
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0006_auto_20171211_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=b'title'),
        ),
    ]
