# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0007_auto_20171211_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='sub_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=512, null=True, unique=True),
        ),
    ]
