# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 15:26
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0008_auto_20171211_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=b'title', unique=True),
        ),
        migrations.AlterField(
            model_name='myfeed',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=512, null=True),
        ),
    ]
