# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appes', '0009_auto_20171211_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeed',
            name='sub_link',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
